USE [master]
GO

/****** Object:  Database [CyberClub]    Script Date: 06.06.2023 11:03:21 ******/
CREATE DATABASE [CyberClub]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CyberClub_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CyberClub.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CyberClub_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CyberClub.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CyberClub].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CyberClub] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CyberClub] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CyberClub] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CyberClub] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CyberClub] SET ARITHABORT OFF 
GO

ALTER DATABASE [CyberClub] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CyberClub] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CyberClub] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CyberClub] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CyberClub] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CyberClub] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CyberClub] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CyberClub] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CyberClub] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CyberClub] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CyberClub] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CyberClub] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CyberClub] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CyberClub] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CyberClub] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CyberClub] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CyberClub] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CyberClub] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CyberClub] SET  MULTI_USER 
GO

ALTER DATABASE [CyberClub] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CyberClub] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CyberClub] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CyberClub] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CyberClub] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CyberClub] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CyberClub] SET QUERY_STORE = ON
GO

ALTER DATABASE [CyberClub] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CyberClub] SET  READ_WRITE 
GO

